import type { RenderStep } from '../../../types/leetcode.types.js';
import { LEET_SENTINEL } from '../../../types/constants.js';
import { MAX_HTTP_BODY_BYTES } from '../http/http-case.helpers.js';

/**
 * Toolchain the render driver needs, installed into the shared cache beside the
 * artifact's own `libs:` — never into this repository's `package.json`, which
 * ships zero runtime dependencies.
 *
 * `esbuild` because `stripTypeScriptTypes` cannot turn JSX into anything
 * runnable (spike §6), and it bundles bare imports in the same pass; `jsdom`
 * because a component has to mount somewhere.
 */
export const HARNESS_LIBS = ['esbuild@^0.25.0', 'jsdom@^26.0.0'] as const;

/** Filename of the generated driver inside the run directory. */
export const RENDER_RUNNER = 'leet-render-runner.js';

/**
 * Per-request budget for a mounted component's own `fetch` (T4.3, VSX-180).
 *
 * Not yet the artifact's own `test.timeoutMs` — `RenderSpec` carries no case
 * budget today, only the render-wide {@link RENDER_TIMEOUT_MS}-style wall
 * clock the caller in `checks.ts` already enforces around the whole child
 * process. A fixed, generous per-request bound closes S11 without that
 * plumbing; threading the artifact's own budget through is a follow-up, not
 * a silent gap — an unbounded request would otherwise burn the *whole*
 * render timeout on one hung fetch.
 */
export const FETCH_TIMEOUT_MS = 10_000;

/** One case: a sequence of steps whose last reading step is the observed value. */
export interface RenderCase {
	/** Zero-based index in the suite — echoed back on the sentinel line */
	index: number;
	/** Steps to perform, in order */
	steps: RenderStep[];
}

/** Everything the generated runner needs to bundle, mount, and drive a component. */
export interface RenderSpec {
	/** Component entry, relative to the run directory (`.jsx` / `.tsx` / `.js`) */
	entry: string;
	/** Shared cache directory holding `node_modules` for the toolchain and the artifact's libs */
	cacheDir: string;
	/** Cases to run, in order */
	cases: RenderCase[];
	/**
	 * The loopback port a live backend was booted on for this run (T4.3,
	 * VSX-180) — never discovered, guessed or defaulted inside the driver.
	 * Omitted (or `undefined`) means no backend: the generated driver's
	 * `fetch` then refuses every request by name rather than reaching the
	 * real network, which is the closed default, not an open one a caller
	 * must remember to lock down.
	 */
	apiPort?: number;
}

/**
 * Command that runs the generated driver, with the run directory as `cwd`.
 *
 * @returns Fixed literal command — no user data is interpolated into it.
 *
 * @example
 * renderRunnerCommand(); // → 'node leet-render-runner.js'
 */
export function renderRunnerCommand(): string {
	return `node ${RENDER_RUNNER}`;
}

/**
 * Generate the driver that bundles a component with esbuild, mounts it in
 * jsdom, and drives one case per sentinel line.
 *
 * **Nothing is interpolated as code.** The entry path, the cache directory and
 * every case are embedded as JSON literals, so an artifact-authored selector or
 * path is data inside the generated program, never syntax. The component's own
 * source is never spliced either — esbuild reads it from disk, exactly as the
 * function environments hand the candidate to a driver rather than into one.
 *
 * Each case **remounts** the component into a fresh container: a project's
 * per-case isolation would otherwise depend on React state left over from the
 * previous case, which is precisely the "pure per call" contract the format spec
 * states for every other test type.
 *
 * Each case is wrapped in its own try/catch, so a component that throws — or
 * non-erasable syntax esbuild refuses — fails that case with the runtime's own
 * message instead of taking the process down.
 *
 * **A component may now call `fetch` (T4.3, VSX-180)**, against a live
 * backend this run itself booted — `spec.apiPort` names the one loopback port
 * it may ever reach. The driver settles every in-flight fetch before each
 * step acts or reads, so a `text`/`count`/`attr`/`style` step never observes
 * a component mid-request. **Visibility stays ungradeable regardless** —
 * jsdom still computes no layout, so a component that fetches real data and
 * then renders it under `display: none` still passes; a live backend answers
 * "is the data right", never "is the component visible".
 *
 * @param spec - Entry, cache directory, cases, and the assigned backend port.
 * @returns Source of a self-contained CommonJS program.
 *
 * @example
 * renderRunnerSource({ entry: 'src/App.jsx', cacheDir: '/tmp/cache', cases: [{ index: 0, steps: [] }] });
 */
export function renderRunnerSource(spec: RenderSpec): string {
	return [
		'// Generated by the project render driver — do not edit.',
		"const path = require('path');",
		`const CACHE = ${JSON.stringify(spec.cacheDir)};`,
		`const ENTRY = ${JSON.stringify(spec.entry)};`,
		`const CASES = ${JSON.stringify(spec.cases)};`,
		`const API_PORT = ${JSON.stringify(spec.apiPort ?? null)};`,
		`const SENTINEL = ${JSON.stringify(LEET_SENTINEL)};`,
		'',
		'// Resolve the toolchain out of the shared cache, never this repo.',
		"const MODULES = path.join(CACHE, 'node_modules');",
		'const req = name => require(require.resolve(name, { paths: [MODULES] }));',
		'',
		'/** One sentinel line per case — the solver\'s own console output cannot be mistaken for it. */',
		String.raw`function emit(payload) { process.stdout.write(SENTINEL + JSON.stringify(payload) + "\n"); }`,
		'',
		FETCH_GUARD_BLOCK,
		'',
		BUNDLE_BLOCK,
		'',
		DOM_BLOCK,
		'',
		STEP_BLOCK,
		'',
		MAIN_BLOCK,
	].join('\n');
}

/**
 * Guarded network access for a mounted component (T4.3, VSX-180) — a
 * self-contained test seam as well as a generated block: exported so a test
 * can prove the loopback check is live without paying for esbuild, jsdom or
 * React.
 *
 * **S10 — the host check lives inside the function `fetch` itself is
 * replaced with, not in whatever calls {@link renderRunnerSource}.** The
 * component under test is the artifact's own `# Solutions` overlay —
 * untrusted, exactly like every other artifact-authored file this extension
 * runs — and a check on *this module's* good behaviour says nothing about a
 * `fetch()` the rendered component decides to make on its own. `installFetch`
 * therefore replaces `global.fetch` with a function that resolves whatever
 * URL it is given (relative or absolute) against `127.0.0.1:<port>` through
 * the platform's own WHATWG `URL` parser and refuses anything that resolves
 * to a different `host` string — an allowlist compare, so a request naming
 * `localhost:<port>` (the *same* server, a different spelling) is refused
 * exactly as one naming a real external host would be; nothing here decides
 * "is this loopback", only "does this equal the one host string this run
 * assigned".
 *
 * This mirrors `http-case.helpers.ts`'s `buildLoopbackUrl` (S1) rather than
 * importing it: this whole file's output is a *string*, executed by a
 * separate `node <runner>.js` process that only ever `require`s from the
 * shared toolchain cache, never from this extension — there is no import to
 * share across that boundary, so the rule is copied, not the module.
 * `LEET_MAX_BODY_BYTES` is the one number both copies still share:
 * {@link MAX_HTTP_BODY_BYTES} baked in at generation time.
 *
 * **The default is refusal.** Before this task nothing touched
 * `global.fetch` inside the generated driver at all, so a component that
 * happened to call it reached Node's own, completely unbounded `fetch` —
 * every `# Solutions` overlay, on every `verify-exercise` sweep. `apiPort:
 * null` (no backend assigned) now installs a `fetch` that always rejects, so
 * a render check gains a network primitive only when a caller explicitly
 * hands it a port — never by omission.
 */
export const FETCH_GUARD_BLOCK = `
var LEET_MAX_BODY_BYTES = ${JSON.stringify(MAX_HTTP_BODY_BYTES)};
var LEET_FETCH_TIMEOUT_MS = ${JSON.stringify(FETCH_TIMEOUT_MS)};
var LEET_REAL_FETCH = global.fetch;
var LEET_REAL_RESPONSE = global.Response;

/** Resolve \`input\` (a string, a \`URL\`, or a \`Request\`-like object) against the one assigned loopback host, refusing anything that resolves off it. */
function leetResolveUrl(input, expectedHost) {
	var raw = typeof input === 'string' ? input
		: (input && typeof input.href === 'string') ? input.href
		: (input && typeof input.url === 'string') ? input.url
		: String(input);
	var url;
	try {
		url = new URL(raw, 'http://' + expectedHost);
	} catch (e) {
		throw new Error('LEET_FETCH_REFUSED: ' + JSON.stringify(raw) + ' is not a valid URL');
	}
	if (url.host !== expectedHost) {
		throw new Error(
			'LEET_FETCH_REFUSED: ' + JSON.stringify(raw) + ' does not resolve to the assigned loopback '
			+ 'backend (' + expectedHost + ') — a rendered component may only reach the port this run '
			+ 'booted, never an artifact-chosen host');
	}
	return url;
}

/** Read a response body under \`LEET_MAX_BODY_BYTES\`, failing loudly rather than truncating (mirrors \`http-case.helpers.ts\`'s S11 bound). */
async function leetReadBoundedBody(response) {
	var reader = response.body ? response.body.getReader() : null;
	if (!reader) { return ''; }
	var chunks = [];
	var total = 0;
	for (;;) {
		var step = await reader.read();
		if (step.done) { break; }
		total += step.value.byteLength;
		if (total > LEET_MAX_BODY_BYTES) {
			await reader.cancel().catch(function () { /* already failing */ });
			throw new Error('LEET_FETCH_REFUSED: response exceeded ' + LEET_MAX_BODY_BYTES + ' bytes');
		}
		chunks.push(step.value);
	}
	return Buffer.concat(chunks).toString('utf8');
}

/** The real request, bounded by a timeout and never following a redirect off this run's own backend (S1's second half — see \`http-case.helpers.ts\`'s \`runHttpCase\`). */
async function leetBoundedFetch(url, init) {
	var response;
	try {
		response = await LEET_REAL_FETCH(url, Object.assign({}, init, {
			redirect: 'manual',
			signal: AbortSignal.timeout(LEET_FETCH_TIMEOUT_MS),
		}));
	} catch (e) {
		if (e && (e.name === 'TimeoutError' || e.name === 'AbortError')) {
			throw new Error('LEET_FETCH_REFUSED: request timed out after ' + LEET_FETCH_TIMEOUT_MS + 'ms');
		}
		throw e;
	}
	var text = await leetReadBoundedBody(response);
	return new LEET_REAL_RESPONSE(text, { status: response.status, statusText: response.statusText, headers: response.headers });
}

/** Replace \`global.fetch\` with the guarded version and return the pending-request set the driver settles before every step. \`port === null\` refuses everything — the closed default. */
function installFetch(port) {
	var pending = new Set();
	if (port === null) {
		global.fetch = function () {
			return Promise.reject(new Error('LEET_FETCH_REFUSED: no live backend is configured for this render check'));
		};
		return pending;
	}
	var expectedHost = '127.0.0.1:' + port;
	global.fetch = function leetGuardedFetch(input, init) {
		var url;
		try {
			url = leetResolveUrl(input, expectedHost);
		} catch (e) {
			return Promise.reject(e);
		}
		var promise = leetBoundedFetch(url, init);
		pending.add(promise);
		// \`.then(forget, forget)\` deliberately, not \`.finally()\`: a \`.finally()\`
		// callback's derived promise rejects right along with \`promise\` when the
		// request fails, and nothing here ever consumes that derived promise —
		// an unhandled rejection that crashes the whole driver process on the
		// very first refused or failed fetch. Passing the same handler as both
		// arguments to \`.then()\` always resolves the derived promise, so the
		// *only* rejection anyone still has to handle is the \`promise\` returned
		// below, which the component's own \`.catch()\` (or \`settlePending\`'s
		// \`Promise.allSettled\`) already does.
		var forget = function () { pending.delete(promise); };
		promise.then(forget, forget);
		return promise;
	};
	return pending;
}

/** Drain every fetch the component has in flight — settled *before* a step acts or reads, so a case never observes a request mid-flight. */
async function settlePending(pending) {
	while (pending.size > 0) {
		await Promise.allSettled(Array.from(pending));
	}
}`.trim();

/**
 * Bundle the entry with esbuild: JSX and TS in one pass, bare imports resolved
 * from the cache.
 *
 * React is deliberately **external**. Bundling it would give the component its
 * own copy while the driver mounts with another, and two Reacts in one process
 * means every hook throws "Invalid hook call" — the component's `require('react')`
 * is instead served by the driver's own resolver, so both share one instance.
 */
const BUNDLE_BLOCK = `
const SHARED = ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime', 'react/jsx-dev-runtime'];

function bundle() {
	const esbuild = req('esbuild');
	const result = esbuild.buildSync({
		entryPoints: [ENTRY],
		bundle: true,
		write: false,
		format: 'cjs',
		platform: 'browser',
		jsx: 'automatic',
		loader: { '.js': 'jsx' },
		nodePaths: [MODULES],
		external: SHARED,
		logLevel: 'silent',
	});
	return result.outputFiles[0].text;
}`.trim();

/** Install a jsdom window as the globals React expects, once per process. */
const DOM_BLOCK = `
function installDom() {
	const { JSDOM } = req('jsdom');
	const dom = new JSDOM('<!doctype html><html><body></body></html>', { pretendToBeVisual: true });
	const win = dom.window;
	global.window = win;
	global.document = win.document;
	global.navigator = win.navigator;
	for (const name of ['HTMLElement', 'Element', 'Node', 'Event', 'MouseEvent', 'getComputedStyle']) {
		global[name] = win[name];
	}
	global.IS_REACT_ACT_ENVIRONMENT = true;
	return win;
}`.trim();

/**
 * Perform one step. Reading steps return a value; acting steps return undefined,
 * so a case's observed value is its last *reading* step.
 */
const STEP_BLOCK = `
function required(root, selector) {
	const node = root.querySelector(selector);
	if (!node) { throw new Error('no element matches ' + JSON.stringify(selector)); }
	return node;
}

// A \`change\` step writes through the prototype \`value\` setter, which ignores
// both \`readOnly\` and \`disabled\` — so a field no user could type into would
// register a state change and grade **green**. That is the one unfaithful path,
// and it is refused here.
//
// A \`click\` deliberately gets NO such guard. A disabled target is already inert
// for the driver exactly as it is for a real user: React never fires the
// handler, so the case observes the no-op it should. Refusing the step instead
// fails a solver who correctly disables a completed control — an occupied
// tic-tac-toe square, a submitted button — which is idiomatic, and which several
// suites script clicks against precisely to assert the no-op.
function writable(root, selector) {
	const node = required(root, selector);
	const why = node.disabled ? 'disabled' : (node.readOnly ? 'readOnly' : null);
	if (why) {
		throw new Error(JSON.stringify(selector) + ' is ' + why + ' — a user could not type into it');
	}
	return node;
}

function perform(root, step, win, act) {
	switch (step.op) {
		case 'click':
			act(() => required(root, step.selector).dispatchEvent(
				new win.MouseEvent('click', { bubbles: true, cancelable: true })));
			return undefined;
		case 'change': {
			const node = writable(root, step.selector);
			act(() => {
				const setter = Object.getOwnPropertyDescriptor(node.constructor.prototype, 'value');
				if (setter && setter.set) { setter.set.call(node, step.value); } else { node.value = step.value; }
				node.dispatchEvent(new win.Event('input', { bubbles: true }));
				node.dispatchEvent(new win.Event('change', { bubbles: true }));
			});
			return undefined;
		}
		case 'text':
			return required(root, step.selector).textContent;
		case 'count':
			return root.querySelectorAll(step.selector).length;
		case 'attr':
			return required(root, step.selector).getAttribute(step.name);
		case 'style':
			// Declared/inline value only. \`getComputedStyle\` is deliberately not
			// used: jsdom computes no layout, so a box-model read would be a
			// confident zero rather than an answer.
			return required(root, step.selector).style[step.property] || null;
		default:
			throw new Error('unknown step ' + JSON.stringify(step.op));
	}
}`.trim();

/**
 * Mount fresh per case, run its steps, report the last read value.
 *
 * `main` is `async` (T4.3): a step may need to wait on a component's own
 * in-flight `fetch` before it is safe to act on or read the DOM, and
 * `settlePending` is itself async. The top-level call is a `.catch`, not a
 * `try`/`await` — this file is CommonJS, and top-level `await` is an ESM-only
 * feature.
 */
const MAIN_BLOCK = `
async function main() {
	const pending = installFetch(API_PORT);
	const win = installDom();
	const code = bundle();
	const React = req('react');
	const { createRoot } = req('react-dom/client');
	const act = React.act || req('react-dom/test-utils').act;

	const mod = { exports: {} };
	new Function('module', 'exports', 'require', 'window', 'document', code)(
		mod, mod.exports, req, win, win.document);
	const Component = mod.exports.default || mod.exports;
	if (typeof Component !== 'function') {
		throw new Error('component entry has no default export that is a component');
	}

	for (const testCase of CASES) {
		const started = Date.now();
		const container = win.document.createElement('div');
		win.document.body.appendChild(container);
		try {
			// Remount per case — no state may leak from the previous one.
			const root = createRoot(container);
			act(() => root.render(React.createElement(Component)));

			let observed = null;
			for (const step of testCase.steps) {
				// Settle every in-flight fetch before acting or reading — a step
				// that reads before the component's own fetch resolves is a false
				// pass, the whole failure mode a live backend invites (T4.3).
				await act(async () => { await settlePending(pending); });
				const value = perform(container, step, win, act);
				if (value !== undefined) { observed = value; }
			}

			emit({ index: testCase.index, actual: JSON.stringify(observed), ms: Date.now() - started });
			act(() => root.unmount());
		} catch (e) {
			emit({ index: testCase.index, error: (e && e.message) || String(e), ms: Date.now() - started });
		} finally {
			container.remove();
		}
	}
}

main().catch((e) => {
	// A failure before any case could run — bundling, installing the fetch
	// guard, or a missing toolchain — is reported against every case rather
	// than as a silent empty suite.
	for (const testCase of CASES) {
		emit({ index: testCase.index, error: (e && e.message) || String(e), ms: 0 });
	}
});`.trim();
