import type { RenderStep } from '../../../types/leetcode.types.js';
import { LEET_SENTINEL } from '../../../types/constants.js';

/**
 * Toolchain the render driver needs, installed into the shared cache beside the
 * artifact's own `libs:` — never into this repository's `package.json`, which
 * ships zero runtime dependencies.
 *
 * `esbuild` because `stripTypeScriptTypes` cannot turn JSX into anything
 * runnable (spike §6), and it bundles bare imports in the same pass; `jsdom`
 * because a component has to mount somewhere.
 */
export const HARNESS_LIBS = ['esbuild@^0.25.0', 'jsdom@^26.0.0'] as const;

/** Filename of the generated driver inside the run directory. */
export const RENDER_RUNNER = 'leet-render-runner.js';

/** One case: a sequence of steps whose last reading step is the observed value. */
export interface RenderCase {
	/** Zero-based index in the suite — echoed back on the sentinel line */
	index: number;
	/** Steps to perform, in order */
	steps: RenderStep[];
}

/** Everything the generated runner needs to bundle, mount, and drive a component. */
export interface RenderSpec {
	/** Component entry, relative to the run directory (`.jsx` / `.tsx` / `.js`) */
	entry: string;
	/** Shared cache directory holding `node_modules` for the toolchain and the artifact's libs */
	cacheDir: string;
	/** Cases to run, in order */
	cases: RenderCase[];
}

/**
 * Command that runs the generated driver, with the run directory as `cwd`.
 *
 * @returns Fixed literal command — no user data is interpolated into it.
 *
 * @example
 * renderRunnerCommand(); // → 'node leet-render-runner.js'
 */
export function renderRunnerCommand(): string {
	return `node ${RENDER_RUNNER}`;
}

/**
 * Generate the driver that bundles a component with esbuild, mounts it in
 * jsdom, and drives one case per sentinel line.
 *
 * **Nothing is interpolated as code.** The entry path, the cache directory and
 * every case are embedded as JSON literals, so an artifact-authored selector or
 * path is data inside the generated program, never syntax. The component's own
 * source is never spliced either — esbuild reads it from disk, exactly as the
 * function environments hand the candidate to a driver rather than into one.
 *
 * Each case **remounts** the component into a fresh container: a project's
 * per-case isolation would otherwise depend on React state left over from the
 * previous case, which is precisely the "pure per call" contract the format spec
 * states for every other test type.
 *
 * Each case is wrapped in its own try/catch, so a component that throws — or
 * non-erasable syntax esbuild refuses — fails that case with the runtime's own
 * message instead of taking the process down.
 *
 * @param spec - Entry, cache directory, and cases.
 * @returns Source of a self-contained CommonJS program.
 *
 * @example
 * renderRunnerSource({ entry: 'src/App.jsx', cacheDir: '/tmp/cache', cases: [{ index: 0, steps: [] }] });
 */
export function renderRunnerSource(spec: RenderSpec): string {
	return [
		'// Generated by the project render driver — do not edit.',
		"const path = require('path');",
		`const CACHE = ${JSON.stringify(spec.cacheDir)};`,
		`const ENTRY = ${JSON.stringify(spec.entry)};`,
		`const CASES = ${JSON.stringify(spec.cases)};`,
		`const SENTINEL = ${JSON.stringify(LEET_SENTINEL)};`,
		'',
		'// Resolve the toolchain out of the shared cache, never this repo.',
		"const MODULES = path.join(CACHE, 'node_modules');",
		'const req = name => require(require.resolve(name, { paths: [MODULES] }));',
		'',
		'/** One sentinel line per case — the solver\'s own console output cannot be mistaken for it. */',
		String.raw`function emit(payload) { process.stdout.write(SENTINEL + JSON.stringify(payload) + "\n"); }`,
		'',
		BUNDLE_BLOCK,
		'',
		DOM_BLOCK,
		'',
		STEP_BLOCK,
		'',
		MAIN_BLOCK,
	].join('\n');
}

/**
 * Bundle the entry with esbuild: JSX and TS in one pass, bare imports resolved
 * from the cache.
 *
 * React is deliberately **external**. Bundling it would give the component its
 * own copy while the driver mounts with another, and two Reacts in one process
 * means every hook throws "Invalid hook call" — the component's `require('react')`
 * is instead served by the driver's own resolver, so both share one instance.
 */
const BUNDLE_BLOCK = `
const SHARED = ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime', 'react/jsx-dev-runtime'];

function bundle() {
	const esbuild = req('esbuild');
	const result = esbuild.buildSync({
		entryPoints: [ENTRY],
		bundle: true,
		write: false,
		format: 'cjs',
		platform: 'browser',
		jsx: 'automatic',
		loader: { '.js': 'jsx' },
		nodePaths: [MODULES],
		external: SHARED,
		logLevel: 'silent',
	});
	return result.outputFiles[0].text;
}`.trim();

/** Install a jsdom window as the globals React expects, once per process. */
const DOM_BLOCK = `
function installDom() {
	const { JSDOM } = req('jsdom');
	const dom = new JSDOM('<!doctype html><html><body></body></html>', { pretendToBeVisual: true });
	const win = dom.window;
	global.window = win;
	global.document = win.document;
	global.navigator = win.navigator;
	for (const name of ['HTMLElement', 'Element', 'Node', 'Event', 'MouseEvent', 'getComputedStyle']) {
		global[name] = win[name];
	}
	global.IS_REACT_ACT_ENVIRONMENT = true;
	return win;
}`.trim();

/**
 * Perform one step. Reading steps return a value; acting steps return undefined,
 * so a case's observed value is its last *reading* step.
 */
const STEP_BLOCK = `
function required(root, selector) {
	const node = root.querySelector(selector);
	if (!node) { throw new Error('no element matches ' + JSON.stringify(selector)); }
	return node;
}

// A \`change\` step writes through the prototype \`value\` setter, which ignores
// both \`readOnly\` and \`disabled\` — so a field no user could type into would
// register a state change and grade **green**. That is the one unfaithful path,
// and it is refused here.
//
// A \`click\` deliberately gets NO such guard. A disabled target is already inert
// for the driver exactly as it is for a real user: React never fires the
// handler, so the case observes the no-op it should. Refusing the step instead
// fails a solver who correctly disables a completed control — an occupied
// tic-tac-toe square, a submitted button — which is idiomatic, and which several
// suites script clicks against precisely to assert the no-op.
function writable(root, selector) {
	const node = required(root, selector);
	const why = node.disabled ? 'disabled' : (node.readOnly ? 'readOnly' : null);
	if (why) {
		throw new Error(JSON.stringify(selector) + ' is ' + why + ' — a user could not type into it');
	}
	return node;
}

function perform(root, step, win, act) {
	switch (step.op) {
		case 'click':
			act(() => required(root, step.selector).dispatchEvent(
				new win.MouseEvent('click', { bubbles: true, cancelable: true })));
			return undefined;
		case 'change': {
			const node = writable(root, step.selector);
			act(() => {
				const setter = Object.getOwnPropertyDescriptor(node.constructor.prototype, 'value');
				if (setter && setter.set) { setter.set.call(node, step.value); } else { node.value = step.value; }
				node.dispatchEvent(new win.Event('input', { bubbles: true }));
				node.dispatchEvent(new win.Event('change', { bubbles: true }));
			});
			return undefined;
		}
		case 'text':
			return required(root, step.selector).textContent;
		case 'count':
			return root.querySelectorAll(step.selector).length;
		case 'attr':
			return required(root, step.selector).getAttribute(step.name);
		case 'style':
			// Declared/inline value only. \`getComputedStyle\` is deliberately not
			// used: jsdom computes no layout, so a box-model read would be a
			// confident zero rather than an answer.
			return required(root, step.selector).style[step.property] || null;
		default:
			throw new Error('unknown step ' + JSON.stringify(step.op));
	}
}`.trim();

/** Mount fresh per case, run its steps, report the last read value. */
const MAIN_BLOCK = `
function main() {
	const win = installDom();
	const code = bundle();
	const React = req('react');
	const { createRoot } = req('react-dom/client');
	const act = React.act || req('react-dom/test-utils').act;

	const mod = { exports: {} };
	new Function('module', 'exports', 'require', 'window', 'document', code)(
		mod, mod.exports, req, win, win.document);
	const Component = mod.exports.default || mod.exports;
	if (typeof Component !== 'function') {
		throw new Error('component entry has no default export that is a component');
	}

	for (const testCase of CASES) {
		const started = Date.now();
		const container = win.document.createElement('div');
		win.document.body.appendChild(container);
		try {
			// Remount per case — no state may leak from the previous one.
			const root = createRoot(container);
			act(() => root.render(React.createElement(Component)));

			let observed = null;
			for (const step of testCase.steps) {
				const value = perform(container, step, win, act);
				if (value !== undefined) { observed = value; }
			}

			emit({ index: testCase.index, actual: JSON.stringify(observed), ms: Date.now() - started });
			act(() => root.unmount());
		} catch (e) {
			emit({ index: testCase.index, error: (e && e.message) || String(e), ms: Date.now() - started });
		} finally {
			container.remove();
		}
	}
}

try {
	main();
} catch (e) {
	// A failure before any case could run — bundling, or a missing toolchain —
	// is reported against every case rather than as a silent empty suite.
	for (const testCase of CASES) {
		emit({ index: testCase.index, error: (e && e.message) || String(e), ms: 0 });
	}
}`.trim();
